import = ["~/.config/alacritty/catppuccin/catppuccin-mocha.toml"]

[env]
TERM = "xterm-256color"

[window]
padding.x = 10
padding.y = 10


opacity = 0.5
blur = true

option_as_alt = "Both"

[font]
normal.family = "MonoLisa Nerd Font"
normal.style = "Regular"

size = 14

offset.y = 2
